// ===== SONORISE DİL SİSTEMİ =====

const translations = {
    az: {
        // Navbar
        nav_home: 'Ana səhifə',
        nav_features: 'Xüsusiyyətlər',
        nav_calculator: 'Kalkulyator',
        nav_modules: 'Modullar',
        nav_hardware: 'Texnologiya',
        nav_login: 'Daxil ol',
        nav_register: 'Qeydiyyat',
        nav_myaccount: 'Hesabım',
        nav_dashboard: 'Dashboard',
        nav_orders: 'Sifarişlərim',
        nav_logout: 'Çıxış',
        nav_back: 'Geri',

        // Hero
        hero_title_1: 'Səs-küyü',
        hero_title_2: 'Enerjiyə',
        hero_title_3: 'Çevirin',
        hero_subtitle: 'Şəhər səs-küyü və sənaye mühitlərindən elektrik enerjisi istehsal edən innovativ texnologiya',
        hero_stat1: 'Modul başına güc',
        hero_stat2: 'Fasiləsiz istehsal',
        hero_stat3: '1 ildə azaldılan (karbon tullantısı) miqdarı',
        hero_btn: 'İndi Başlayın',

        // Features
        features_title: 'Necə İşləyir?',
        feature1_title: 'Səs Dalğaları',
        feature1_desc: 'Avtomobil, zavod və ictimai yerlərdən gələn səs-küy tutulur',
        feature2_title: 'Mexaniki Çevrilmə',
        feature2_desc: 'Piezoelektrik kristallar mexaniki təzyiqi birbaşa elektrik gərginliyinə çevirir',
        feature3_title: 'Enerji İstehsalı',
        feature3_desc: 'Super-kondensatorlar və ya batareya modulları vasitəsilə mexaniki enerji elektrik enerjisinə çevrilir və saxlanılır',

        // Calculator
        calc_title: 'Təsir Kalkulyatoru',
        calc_intro: 'Sizin yanınızda gördüyünüz bu prototip bizim texnologiyamızın nüvəsidir. Aşağıdakı kalkulyator vasitəsilə bu texnologiyanın böyük sənaye sahələrində yaradacağı real təsirini görə bilərsiniz.',
        calc_module_count: 'Modul Sayı',
        calc_energy: 'İllik Enerji İstehsalı',
        calc_carbon: 'İllik CO₂ Azalması',
        calc_savings: 'İllik Qənaət (təxmini)',

        // Modules showcase
        modules_title: 'Modul Növləri',
        mod1_title: 'Yol Kənarı',
        mod1_desc: 'Avtomobil səs-küyündən enerji (Cihaz, dirəyə montaj və baza bulud monitorinqi daxildir)',
        mod2_title: 'Sənaye',
        mod2_desc: 'Zavod və fabrik səs-küyü (Ağır sənaye şəraitinə davamlı korpus və 10 illik texniki servis xidməti daxildir.)',
        mod3_title: 'İctimai Yerlər',
        mod3_desc: 'Konsert, stadion və s. (Daha yüksək həssaslıqlı sensorlar və rütubətə qarşı xüsusi müdafiə qatı daxildir)',
        mod4_title: 'Metro/Tunel',
        mod4_desc: 'Nəqliyyat tunellərində (Rütubət və toza qarşı cihazın korpusunun xüsusi olaraq izolyasiya olunması daxildir)',

        // Hardware
        hardware_title: 'Hardware Texnologiyası',
        hw1_title: 'Piezoelektrik Kristallar',
        hw1_desc: 'Səs dalğalarını mexaniki təzyiqə çevirən xüsusi kristallar. Hər bir kristal 0.1-1W enerji istehsal edir.',
        hw2_title: 'Rezonans Kamerası',
        hw2_desc: 'Səs dalğalarını gücləndirir və optimal tezliyə gətirir. 60-110 dB arası səslər üçün ən effektivdir.',
        hw3_title: 'Enerji Saxlama',
        hw3_desc: 'Kondensator və kiçik batareyalar vasitəsilə istehsal olunan enerji saxlanılır və stabilləşdirilir.',
        hw4_title: 'Smart İdarəetmə',
        hw4_desc: 'IoT sensorları real-time enerji istehsalını monitorinq edir və optimize edir.',

        // Footer
        footer: '© 2026 SonoRise Platform',

        // Login
        login_title: 'Giriş',
        login_email: 'Email',
        login_password: 'Şifrə',
        login_forgot: 'Şifrəni unutmusunuz?',
        login_btn: 'Daxil ol',
        login_no_account: 'Hesabınız yoxdur?',
        login_register: 'Qeydiyyatdan keçin',
        login_back: 'Ana səhifəyə qayıt',

        // Register
        register_title: 'Qeydiyyat',
        register_name: 'Ad Soyad',
        register_email: 'Email',
        register_password: 'Şifrə',
        register_btn: 'Qeydiyyatdan keç',
        register_have_account: 'Hesabınız var?',
        register_login: 'Daxil olun',
        register_back: 'Ana səhifəyə qayıt',

        // Forgot password
        forgot_title: 'Şifrəni Bərpa Et',
        forgot_email: 'Qeydiyyat Email',
        forgot_btn: 'Bərpa Linki Göndər',
        forgot_back_login: 'Girişə qayıt',
        forgot_back_home: 'Ana səhifəyə qayıt',
        forgot_success: 'Şifrə bərpa linki email ünvanınıza göndərildi. Zəhmət olmasa email qutunuzu yoxlayın.',
        forgot_error: 'Bu email ilə qeydiyyat tapılmadı',

        // Dashboard
        dash_title: 'İdarə Paneli',
        dash_total_modules: 'Ümumi Modullar',
        dash_energy: 'Bu Ay Enerji',
        dash_sound: 'Orta Səs Səviyyəsi',
        dash_co2: 'CO₂ Azalması',
        dash_my_modules: 'Mənim Modullarım',
        dash_new_module: '+ Yeni Modul',
        dash_hello: 'Salam,',
        dash_notifications: 'Bildirişlər',
        dash_notif1: 'Sono-01 pik səmərəliliyə çatdı (+15% enerji)',
        dash_notif2: 'Enerji istehsalı aylıq hədəfi keçdi',
        dash_notif3: 'Səs səviyyəsi 86.5 dB-ə çatdı',
        dash_add_module_title: 'Yeni Modul Əlavə Et',
        dash_add_module_desc: 'Sisteminizə uyğun yeni modulu seçərək şəbəkənizi genişləndirin',
        dash_connect_module: '🔌 Mövcud Modulu Qoş',
        dash_connect_desc: 'Əlinizdə olan SonoRise cihazını sistemə inteqrasiya edin (ID nömrəsi ilə)',
        dash_device_id: 'Cihaz ID: məs. SNR-2026-XXXX',
        dash_device_loc: 'Quraşdırma yeri: məs. Nizami küçəsi 24',
        dash_connect_btn: 'Cihazı Qoş',
        dash_order_module: '🛒 Yeni Modul Sifariş Et',
        dash_order_desc: 'SonoRise modullarına baxın və ehtiyacınıza uyğun olanı seçin',
        dash_see_modules: 'Modulları Gör →',
        dash_daily_chart: '📈 Günlük Enerji Artımı',
        dash_system_health: 'SYSTEM HEALTH',
        dash_status: 'Status',
        dash_stabil: '● Stabil',
        dash_temp: 'Temperatur',
        dash_connection: 'Bağlantı',
        dash_wifi: 'Wi-Fi: Güclü',
        dash_delete: '🗑️ Sil',
        dash_online: '● Online',
        dash_orders_title: 'Sifarişlərim',
        dash_no_orders: 'Hələ sifarişiniz yoxdur',
        dash_order_status: 'Gözləmədə',

        // Modules page
        modules_page_title: 'Modul Növləri',
        modules_page_subtitle: 'Ehtiyacınıza uyğun modulu seçin',
        modules_custom_title: '🔧 Fərdi Modul Sifarişi',
        modules_custom_desc: 'Hazır paket istəmirsinizsə, istədiyiniz sayda modul seçin',
        modules_qty: 'Ədəd',
        modules_total: 'Ümumi məbləğ:',
        modules_order_btn: 'Sifariş Ver',
        modules_max_power: 'Maksimum Güc:',
        modules_optimal_sound: 'Optimal Səs:',
        modules_select_btn: 'Bu Modulu Seç',

        // Order form
        order_title: 'Sifariş Ver',
        order_personal: '👤 Şəxsi Məlumatlar',
        order_name: 'Ad Soyad',
        order_fin: 'FIN Kod',
        order_phone: 'Telefon Nömrəsi',
        order_location_title: '📍 Quraşdırma Yeri',
        order_address: 'Ünvan',
        order_where: 'Hara quraşdırmaq istəyirsiniz?',
        order_card_title: '💳 Kart Məlumatları',
        order_card_num: 'Kart Nömrəsi',
        order_expiry: 'Son İstifadə Tarixi',
        order_cvv: 'CVV',
        order_cancel: 'Ləğv et',
        order_confirm: 'Sifarişi Təsdiqlə ✓',

        // Auth errors
        err_email_format: 'Email formatı düzgün deyil',
        err_temp_email: 'Müvəqqəti email ünvanları qəbul edilmir. Zəhmət olmasa real email istifadə edin.',
        err_wrong_pass: 'Email və ya şifrə səhvdir',
        err_email_exists: 'Bu email artıq qeydiyyatdan keçib',
    },

    en: {
        nav_home: 'Home',
        nav_features: 'Features',
        nav_calculator: 'Calculator',
        nav_modules: 'Modules',
        nav_hardware: 'Technology',
        nav_login: 'Login',
        nav_register: 'Register',
        nav_myaccount: 'My Account',
        nav_dashboard: 'Dashboard',
        nav_orders: 'My Orders',
        nav_logout: 'Logout',
        nav_back: 'Back',

        hero_title_1: 'Convert',
        hero_title_2: 'Noise',
        hero_title_3: 'to Energy',
        hero_subtitle: 'Innovative technology that generates electricity from urban noise and industrial environments',
        hero_stat1: 'Power per module',
        hero_stat2: 'Continuous production',
        hero_stat3: 'Carbon reduced per year',
        hero_btn: 'Get Started',

        features_title: 'How It Works?',
        feature1_title: 'Sound Waves',
        feature1_desc: 'Noise from cars, factories and public places is captured',
        feature2_title: 'Mechanical Conversion',
        feature2_desc: 'Piezoelectric crystals convert mechanical pressure directly into electrical voltage',
        feature3_title: 'Energy Production',
        feature3_desc: 'Mechanical energy is converted and stored as electrical energy via supercapacitors or battery modules',

        calc_title: 'Impact Calculator',
        calc_intro: 'The prototype you see next to you is the core of our technology. Use the calculator below to see the real impact this technology will create in large industrial areas.',
        calc_module_count: 'Module Count',
        calc_energy: 'Annual Energy Production',
        calc_carbon: 'Annual CO₂ Reduction',
        calc_savings: 'Annual Savings (estimated)',

        modules_title: 'Module Types',
        mod1_title: 'Roadside',
        mod1_desc: 'Energy from car noise (Device, pole mount and cloud monitoring included)',
        mod2_title: 'Industrial',
        mod2_desc: 'Factory and plant noise (Durable housing for heavy industry and 10-year service included)',
        mod3_title: 'Public Places',
        mod3_desc: 'Concerts, stadiums, etc. (High sensitivity sensors and moisture protection included)',
        mod4_title: 'Metro/Tunnel',
        mod4_desc: 'In transport tunnels (Special insulation against moisture and dust included)',

        hardware_title: 'Hardware Technology',
        hw1_title: 'Piezoelectric Crystals',
        hw1_desc: 'Special crystals that convert sound waves into mechanical pressure. Each crystal produces 0.1-1W of energy.',
        hw2_title: 'Resonance Chamber',
        hw2_desc: 'Amplifies sound waves and brings them to optimal frequency. Most effective for sounds between 60-110 dB.',
        hw3_title: 'Energy Storage',
        hw3_desc: 'Produced energy is stored and stabilized via capacitors and small batteries.',
        hw4_title: 'Smart Control',
        hw4_desc: 'IoT sensors monitor and optimize real-time energy production.',

        footer: '© 2026 SonoRise Platform',

        login_title: 'Login',
        login_email: 'Email',
        login_password: 'Password',
        login_forgot: 'Forgot your password?',
        login_btn: 'Login',
        login_no_account: "Don't have an account?",
        login_register: 'Register',
        login_back: 'Back to Home',

        register_title: 'Register',
        register_name: 'Full Name',
        register_email: 'Email',
        register_password: 'Password',
        register_btn: 'Register',
        register_have_account: 'Already have an account?',
        register_login: 'Login',
        register_back: 'Back to Home',

        forgot_title: 'Reset Password',
        forgot_email: 'Registered Email',
        forgot_btn: 'Send Reset Link',
        forgot_back_login: 'Back to Login',
        forgot_back_home: 'Back to Home',
        forgot_success: 'A password reset link has been sent to your email. Please check your inbox.',
        forgot_error: 'No account found with this email',

        dash_title: 'Dashboard',
        dash_total_modules: 'Total Modules',
        dash_energy: 'This Month Energy',
        dash_sound: 'Average Sound Level',
        dash_co2: 'CO₂ Reduction',
        dash_my_modules: 'My Modules',
        dash_new_module: '+ New Module',
        dash_hello: 'Hello,',
        dash_notifications: 'Notifications',
        dash_notif1: 'Sono-01 reached peak efficiency (+15% energy)',
        dash_notif2: 'Energy production exceeded monthly target',
        dash_notif3: 'Sound level reached 86.5 dB',
        dash_add_module_title: 'Add New Module',
        dash_add_module_desc: 'Expand your network by selecting a new module',
        dash_connect_module: '🔌 Connect Existing Module',
        dash_connect_desc: 'Integrate your SonoRise device into the system (with ID number)',
        dash_device_id: 'Device ID: e.g. SNR-2026-XXXX',
        dash_device_loc: 'Installation location: e.g. Main Street 24',
        dash_connect_btn: 'Connect Device',
        dash_order_module: '🛒 Order New Module',
        dash_order_desc: 'Browse SonoRise modules and choose the right one for you',
        dash_see_modules: 'See Modules →',
        dash_daily_chart: '📈 Daily Energy Growth',
        dash_system_health: 'SYSTEM HEALTH',
        dash_status: 'Status',
        dash_stabil: '● Stable',
        dash_temp: 'Temperature',
        dash_connection: 'Connection',
        dash_wifi: 'Wi-Fi: Strong',
        dash_delete: '🗑️ Delete',
        dash_online: '● Online',
        dash_orders_title: 'My Orders',
        dash_no_orders: 'No orders yet',
        dash_order_status: 'Pending',

        modules_page_title: 'Module Types',
        modules_page_subtitle: 'Choose the module that suits your needs',
        modules_custom_title: '🔧 Custom Module Order',
        modules_custom_desc: 'If you do not want a ready package, choose as many modules as you want',
        modules_qty: 'Quantity',
        modules_total: 'Total amount:',
        modules_order_btn: 'Order',
        modules_max_power: 'Maximum Power:',
        modules_optimal_sound: 'Optimal Sound:',
        modules_select_btn: 'Select This Module',

        order_title: 'Place Order',
        order_personal: '👤 Personal Information',
        order_name: 'Full Name',
        order_fin: 'ID Number',
        order_phone: 'Phone Number',
        order_location_title: '📍 Installation Location',
        order_address: 'Address',
        order_where: 'Where do you want to install it?',
        order_card_title: '💳 Card Information',
        order_card_num: 'Card Number',
        order_expiry: 'Expiry Date',
        order_cvv: 'CVV',
        order_cancel: 'Cancel',
        order_confirm: 'Confirm Order ✓',

        err_email_format: 'Invalid email format',
        err_temp_email: 'Temporary email addresses are not accepted. Please use a real email.',
        err_wrong_pass: 'Incorrect email or password',
        err_email_exists: 'This email is already registered',
    },

    ru: {
        nav_home: 'Главная',
        nav_features: 'Особенности',
        nav_calculator: 'Калькулятор',
        nav_modules: 'Модули',
        nav_hardware: 'Технология',
        nav_login: 'Войти',
        nav_register: 'Регистрация',
        nav_myaccount: 'Мой аккаунт',
        nav_dashboard: 'Панель',
        nav_orders: 'Мои заказы',
        nav_logout: 'Выйти',
        nav_back: 'Назад',

        hero_title_1: 'Превратите',
        hero_title_2: 'Шум',
        hero_title_3: 'в Энергию',
        hero_subtitle: 'Инновационная технология, производящая электроэнергию из городского шума и промышленных сред',
        hero_stat1: 'Мощность на модуль',
        hero_stat2: 'Непрерывное производство',
        hero_stat3: 'Сокращение углерода в год',
        hero_btn: 'Начать сейчас',

        features_title: 'Как это работает?',
        feature1_title: 'Звуковые волны',
        feature1_desc: 'Улавливается шум от автомобилей, заводов и общественных мест',
        feature2_title: 'Механическое преобразование',
        feature2_desc: 'Пьезоэлектрические кристаллы преобразуют механическое давление непосредственно в электрическое напряжение',
        feature3_title: 'Производство энергии',
        feature3_desc: 'Механическая энергия преобразуется и сохраняется как электрическая через суперконденсаторы или аккумуляторные модули',

        calc_title: 'Калькулятор воздействия',
        calc_intro: 'Прототип рядом с вами — это ядро нашей технологии. Используйте калькулятор ниже, чтобы увидеть реальное воздействие этой технологии в крупных промышленных районах.',
        calc_module_count: 'Количество модулей',
        calc_energy: 'Годовое производство энергии',
        calc_carbon: 'Годовое сокращение CO₂',
        calc_savings: 'Годовая экономия (приблизительно)',

        modules_title: 'Типы модулей',
        mod1_title: 'Придорожный',
        mod1_desc: 'Энергия от автомобильного шума (включая устройство, монтаж на столб и облачный мониторинг)',
        mod2_title: 'Промышленный',
        mod2_desc: 'Шум заводов и фабрик (прочный корпус для тяжелой промышленности и 10-летнее обслуживание включены)',
        mod3_title: 'Общественные места',
        mod3_desc: 'Концерты, стадионы и т.д. (высокочувствительные датчики и защита от влаги включены)',
        mod4_title: 'Метро/Тоннель',
        mod4_desc: 'В транспортных тоннелях (специальная изоляция от влаги и пыли включена)',

        hardware_title: 'Аппаратная технология',
        hw1_title: 'Пьезоэлектрические кристаллы',
        hw1_desc: 'Специальные кристаллы, преобразующие звуковые волны в механическое давление. Каждый кристалл производит 0,1-1 Вт энергии.',
        hw2_title: 'Резонансная камера',
        hw2_desc: 'Усиливает звуковые волны и приводит их к оптимальной частоте. Наиболее эффективна для звуков 60-110 дБ.',
        hw3_title: 'Накопление энергии',
        hw3_desc: 'Произведённая энергия хранится и стабилизируется через конденсаторы и небольшие аккумуляторы.',
        hw4_title: 'Умное управление',
        hw4_desc: 'IoT-датчики отслеживают и оптимизируют производство энергии в реальном времени.',

        footer: '© 2026 SonoRise Platform',

        login_title: 'Вход',
        login_email: 'Эл. почта',
        login_password: 'Пароль',
        login_forgot: 'Забыли пароль?',
        login_btn: 'Войти',
        login_no_account: 'Нет аккаунта?',
        login_register: 'Зарегистрироваться',
        login_back: 'Вернуться на главную',

        register_title: 'Регистрация',
        register_name: 'Полное имя',
        register_email: 'Эл. почта',
        register_password: 'Пароль',
        register_btn: 'Зарегистрироваться',
        register_have_account: 'Уже есть аккаунт?',
        register_login: 'Войти',
        register_back: 'Вернуться на главную',

        forgot_title: 'Восстановление пароля',
        forgot_email: 'Зарегистрированный Email',
        forgot_btn: 'Отправить ссылку',
        forgot_back_login: 'Вернуться к входу',
        forgot_back_home: 'Вернуться на главную',
        forgot_success: 'Ссылка для сброса пароля отправлена на ваш email. Пожалуйста, проверьте почту.',
        forgot_error: 'Аккаунт с таким email не найден',

        dash_title: 'Панель управления',
        dash_total_modules: 'Всего модулей',
        dash_energy: 'Энергия за месяц',
        dash_sound: 'Средний уровень звука',
        dash_co2: 'Сокращение CO₂',
        dash_my_modules: 'Мои модули',
        dash_new_module: '+ Новый модуль',
        dash_hello: 'Привет,',
        dash_notifications: 'Уведомления',
        dash_notif1: 'Sono-01 достиг пиковой эффективности (+15% энергии)',
        dash_notif2: 'Производство энергии превысило месячную цель',
        dash_notif3: 'Уровень звука достиг 86.5 дБ',
        dash_add_module_title: 'Добавить новый модуль',
        dash_add_module_desc: 'Расширьте вашу сеть, выбрав новый модуль',
        dash_connect_module: '🔌 Подключить существующий модуль',
        dash_connect_desc: 'Интегрируйте ваше устройство SonoRise в систему (по ID номеру)',
        dash_device_id: 'ID устройства: напр. SNR-2026-XXXX',
        dash_device_loc: 'Место установки: напр. ул. Низами 24',
        dash_connect_btn: 'Подключить устройство',
        dash_order_module: '🛒 Заказать новый модуль',
        dash_order_desc: 'Просмотрите модули SonoRise и выберите подходящий',
        dash_see_modules: 'Смотреть модули →',
        dash_daily_chart: '📈 Суточный рост энергии',
        dash_system_health: 'SYSTEM HEALTH',
        dash_status: 'Статус',
        dash_stabil: '● Стабильно',
        dash_temp: 'Температура',
        dash_connection: 'Соединение',
        dash_wifi: 'Wi-Fi: Сильный',
        dash_delete: '🗑️ Удалить',
        dash_online: '● Online',
        dash_orders_title: 'Мои заказы',
        dash_no_orders: 'Заказов пока нет',
        dash_order_status: 'В ожидании',

        modules_page_title: 'Типы модулей',
        modules_page_subtitle: 'Выберите модуль, подходящий для ваших нужд',
        modules_custom_title: '🔧 Индивидуальный заказ',
        modules_custom_desc: 'Если вы не хотите готовый пакет, выберите нужное количество модулей',
        modules_qty: 'Количество',
        modules_total: 'Итоговая сумма:',
        modules_order_btn: 'Заказать',
        modules_max_power: 'Максимальная мощность:',
        modules_optimal_sound: 'Оптимальный звук:',
        modules_select_btn: 'Выбрать этот модуль',

        order_title: 'Оформить заказ',
        order_personal: '👤 Личные данные',
        order_name: 'Полное имя',
        order_fin: 'Номер удостоверения',
        order_phone: 'Номер телефона',
        order_location_title: '📍 Место установки',
        order_address: 'Адрес',
        order_where: 'Где вы хотите установить?',
        order_card_title: '💳 Данные карты',
        order_card_num: 'Номер карты',
        order_expiry: 'Срок действия',
        order_cvv: 'CVV',
        order_cancel: 'Отмена',
        order_confirm: 'Подтвердить заказ ✓',

        err_email_format: 'Неверный формат email',
        err_temp_email: 'Временные email-адреса не принимаются. Пожалуйста, используйте настоящий email.',
        err_wrong_pass: 'Неверный email или пароль',
        err_email_exists: 'Этот email уже зарегистрирован',
    }
};

// Aktiv dili al
function getLang() {
    return localStorage.getItem('lang') || 'az';
}

// Dili dəyiş
function setLang(lang) {
    localStorage.setItem('lang', lang);
    location.reload();
}

// Tərcümə et
function t(key) {
    const lang = getLang();
    return translations[lang][key] || translations['az'][key] || key;
}

// Dil seçici HTML
function renderLangSwitcher() {
    const lang = getLang();
    return `
        <div class="lang-switcher">
            <button onclick="setLang('az')" class="${lang === 'az' ? 'lang-active' : ''}">AZ</button>
            <button onclick="setLang('en')" class="${lang === 'en' ? 'lang-active' : ''}">EN</button>
            <button onclick="setLang('ru')" class="${lang === 'ru' ? 'lang-active' : ''}">RU</button>
        </div>
    `;
}